# Generated by Django 5.0 on 2023-12-30 14:10

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=notes.models.upload_to, verbose_name='Превью'),
        ),
    ]
